from __future__ import annotations

SCHEMA_VERSION = "1.9.0"
BLOWOUT_MARGIN = 50.0
NAIL_BITER_MARGIN = 5.0
SHOOTOUT_COMBINED = 340.0
SLUGFEST_COMBINED = 260.0
CLOSE_GAME_MARGIN = 20.0
WIN_PCT_PLACES = 4
POINTS_PLACES = 2
DEFAULT_MIN_INTERVAL_SEC = 0.10

__all__ = [
    "SCHEMA_VERSION",
    "BLOWOUT_MARGIN",
    "NAIL_BITER_MARGIN",
    "SHOOTOUT_COMBINED",
    "SLUGFEST_COMBINED",
    "CLOSE_GAME_MARGIN",
    "WIN_PCT_PLACES",
    "POINTS_PLACES",
    "DEFAULT_MIN_INTERVAL_SEC",
]
